[package]
name = "lightsbruh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
cpal = "0.14.2"
rpi-led-panel = "0.2.0"