[build]
default-target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
pre-build = ["dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libasound-dev:armhf"]